/// Flutter icons PetblockApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PetblockApp
///      fonts:
///       - asset: fonts/PetblockApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PetblockApp {
  PetblockApp._();

  static const _kFontFam = 'PetblockApp';
  static const _kFontPkg = null;

  static const IconData appointment = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData msg = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pets = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bone = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData veterinary = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bin = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signout = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
